const root=document.querySelector('.viewer'),csvName=root.dataset.csv;
const colors=['#d62728','#1f77b4','#2ca02c','#9467bd','#ff7f0e','#17becf','#8c564b','#e377c2'];
const preferred=new Set(['roll_deg','pitch_deg','yaw_deg','relative_alt_m','groundspeed_mps','battery_voltage_v','battery_current_a','motor1_pct','motor2_pct','motor3_pct','motor4_pct']);
const modes={0:'STABILIZE',1:'ACRO',2:'ALT HOLD',3:'AUTO',4:'GUIDED',5:'LOITER',6:'RTL',7:'CIRCLE',9:'LAND',11:'DRIFT',13:'SPORT',14:'FLIP',15:'AUTOTUNE',16:'POSHOLD',17:'BRAKE'};
let headers=[],rows=[],elapsed=[],numeric=[],selected=[],cursor=0;
document.querySelectorAll('.viewer-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.viewer-tabs button,.viewer-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')});
fetch('/api/csv/'+csvName).then(r=>{if(!r.ok)throw Error('Unable to load CSV');return r.json()}).then(load).catch(e=>document.getElementById('sample-status').textContent=e.message);
function number(v){if(v===null||v===undefined)return null;const clean=String(v).replace(/\0/g,'').trim();if(clean==='')return null;const n=Number(clean);return Number.isFinite(n)?n:null}
function load(data){headers=data.headers;rows=data.rows;elapsed=rows.map((r,i)=>number(r.elapsed_s)??i);numeric=headers.filter(h=>h!=='elapsed_s'&&h!=='flight_mode'&&rows.some(r=>number(r[h])!==null));selected=numeric.filter(h=>preferred.has(h));if(!selected.length)selected=numeric.slice(0,4);buildSelectors();buildRaw();buildModes();const slider=document.getElementById('time-cursor');slider.max=Math.max(0,rows.length-1);slider.oninput=()=>{cursor=Number(slider.value);draw();updateSample()};window.addEventListener('resize',draw);updateSample();draw()}
function buildSelectors(){const box=document.getElementById('series-list');numeric.forEach(h=>{const label=document.createElement('label');label.className='series-option';label.innerHTML=`<input type="checkbox" ${selected.includes(h)?'checked':''}> ${h}`;label.querySelector('input').onchange=e=>{selected=e.target.checked?[...selected,h]:selected.filter(x=>x!==h);draw()};box.appendChild(label)})}
function buildRaw(){const table=document.getElementById('raw-table');const head=document.createElement('tr');headers.forEach(h=>{const th=document.createElement('th');th.textContent=h;head.appendChild(th)});table.appendChild(head);rows.forEach(r=>{const tr=document.createElement('tr');headers.forEach(h=>{const td=document.createElement('td');td.textContent=r[h]??'';tr.appendChild(td)});table.appendChild(tr)})}
function buildModes(){const line=document.createElement('div');line.className='mode-line';if(!rows.length||!headers.includes('flight_mode'))return;let start=0;for(let i=1;i<=rows.length;i++){if(i===rows.length||rows[i].flight_mode!==rows[start].flight_mode){const seg=document.createElement('div');seg.className='mode-segment';seg.style.width=((i-start)/rows.length*100)+'%';seg.style.background=colors[(line.children.length)%colors.length]+'99';seg.textContent=modes[Number(rows[start].flight_mode)]??('MODE '+rows[start].flight_mode);line.appendChild(seg);start=i}}document.getElementById('mode-timeline').appendChild(line)}
function draw(){const canvas=document.getElementById('log-chart'),dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);const pad={l:55,r:15,t:15,b:35};c.strokeStyle='#ddd';for(let i=0;i<6;i++){const y=pad.t+i*(h-pad.t-pad.b)/5;c.beginPath();c.moveTo(pad.l,y);c.lineTo(w-pad.r,y);c.stroke()}const vals=selected.flatMap(k=>rows.map(r=>number(r[k])).filter(v=>v!==null));if(!vals.length)return;let min=Math.min(...vals),max=Math.max(...vals);if(min===max){min-=.5;max+=.5}const validElapsed=elapsed.filter(Number.isFinite),t0=validElapsed.length?Math.min(...validElapsed):0,t1=validElapsed.length?Math.max(...validElapsed):1,tx=t=>pad.l+(t-t0)/Math.max(t1-t0,1e-9)*(w-pad.l-pad.r),vy=v=>pad.t+(max-v)/(max-min)*(h-pad.t-pad.b);selected.forEach((k,j)=>{c.strokeStyle=colors[j%colors.length];c.lineWidth=1.5;c.beginPath();let begun=false;rows.forEach((r,i)=>{const v=number(r[k]);if(v===null)return;const x=tx(elapsed[i]),y=vy(v);begun?c.lineTo(x,y):c.moveTo(x,y);begun=true});c.stroke();c.fillStyle=colors[j%colors.length];c.fillText(k,pad.l+8+(j%4)*150,12+Math.floor(j/4)*13)});c.strokeStyle='red';c.beginPath();c.moveTo(tx(elapsed[cursor]),pad.t);c.lineTo(tx(elapsed[cursor]),h-pad.b);c.stroke();c.fillStyle='#333';c.fillText(t0.toFixed(1)+' s',pad.l,h-10);c.fillText(t1.toFixed(1)+' s',w-pad.r-45,h-10)}
function updateSample(){if(!rows.length)return;const r=rows[cursor],mode=modes[Number(r.flight_mode)]??(r.flight_mode||'--');document.getElementById('sample-status').textContent=`t = ${Number(elapsed[cursor]).toFixed(3)} s    Mode: ${mode}    Armed: ${r.armed??'--'}    Safety: ${r.safety_released??'--'}    FSM: ${r.fsm_state??'--'}`;const rc=document.getElementById('rc-list');rc.innerHTML='';for(let n=1;n<=18;n++){const v=number(r['rc'+n]),p=v===null?0:Math.max(0,Math.min(100,(v-800)/14)),state=v===null?'--':v<=1250?'LOW':v>=1750?'HIGH':'MID';rc.insertAdjacentHTML('beforeend',`<div class="rc-row"><b>CH${n}</b><div class="rc-bar"><div class="rc-fill" style="width:${p}%"></div></div><span>${v??'--'} ${state}</span></div>`)}}
